version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17
  pre_build:
    commands:
      - npm install
  build:
    commands:
      # 만약 에러가 계속나면 'ls -al'을 추가해서 파일 목록을 로그로 확인해보세요
      - ls -al 
      - ng build --configuration production
artifacts:
  files:
    - '**/*'
  base-directory: 'dist' # 특정 폴더명 대신 dist 전체를 지정
